export const FETCH_GENERAL_NEWS = 'FETCH_GENERAL_NEWS';
export const FETCH_TECH_NEWS = 'FETCH_TECH_NEWS';
export const FETCH_SPORTS_NEWS = 'FETCH_SPORTS_NEWS';

export const SELECTED_POST = 'SELECTED_POST';

export const NEWS_CATEGORIES = 'NEWS_CATEGORIES';

export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF';
